name: Nilmat
version: "1.3"
date: 2017-09-12
description: |
    Computing with nilpotent matrix groups

authors:
    - name: Alla Detinko
      url: https://ad271.host.cs.st-andrews.ac.uk/
    - name: Bettina Eick
      url: http://www.tu-bs.de/~beick
    - name: Dane Flannery
      url: http://www.maths.nuigalway.ie/~dane

maintainers:
    - name: Alla Detinko
      url: https://ad271.host.cs.st-andrews.ac.uk/
    - name: Bettina Eick
      url: http://www.tu-bs.de/~beick
    - name: Dane Flannery
      url: http://www.maths.nuigalway.ie/~dane

GAP: ">=4.4.12"

needed-pkgs:
    - name: "Polenta"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polenta/"

www: http://www.maths.nuigalway.ie/~dane/nilmat
readme: README
packageinfo: http://www.maths.nuigalway.ie/~dane/nilmat/PackageInfo.g

downloads:
    - name: .zip
      url: http://www.maths.nuigalway.ie/~dane/nilmat/nilmat-1.3.zip

abstract: |
    The <span class="pkgname">Nilmat</span> package contains methods for checking whether a finitely generated matrix group over a finite field or the field of rational numbers is nilpotent, methods for computing with such nilpotent matrix groups and methods for constructing important classes of such nilpotent matrix groups.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    nilpotent groups, matrix groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>DEF17</span>]   <b class='BibAuthor'>Detinko, A., Eick, B. and Flannery, D.</b>,
     <i class='BibTitle'>Nilmat, Computing with nilpotent matrix groups,
             Version 1.3</i>
     (<span class='BibYear'>2017</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="http://www.maths.nuigalway.ie/~dane/nilmat">http://www.maths.nuigalway.ie/~dane/nilmat</a></span>.
    </p>
    

bibtex: |
    @misc{ Nilmat1.3,
      author =           {Detinko, A. and Eick, B. and Flannery, D.},
      title =            {{Nilmat}, Computing with nilpotent matrix groups, {V}ersion 1.3},
      month =            {Sep},
      year =             {2017},
      note =             {Refereed GAP package},
      howpublished =     {\href        {http://www.maths.nuigalway.ie/~dane/nilmat}       {\texttt{http://www.maths.nuigalway.ie/}\discretionary       {}{}{}\texttt{\texttt{\symbol{126}}dane/}\discretionary
                          {}{}{}\texttt{nilmat}}},
      keywords =         {nilpotent groups; matrix groups},
      printedkey =       {DEF17}
    }

