name: Nilmat
version: "1.4.1"
date: 2022-02-21
description: |
    Computing with nilpotent matrix groups

authors:
    - name: Alla Detinko
      url: https://ad271.host.cs.st-andrews.ac.uk/
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick/
    - name: Dane Flannery
      url: http://www.maths.nuigalway.ie/~dane

maintainers:
    - name: Alla Detinko
      url: https://ad271.host.cs.st-andrews.ac.uk/
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick/
    - name: Dane Flannery
      url: http://www.maths.nuigalway.ie/~dane

GAP: ">=4.8"

needed-pkgs:
    - name: "Polenta"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polenta/"

www: https://gap-packages.github.io/nilmat
readme: README.md
packageinfo: https://gap-packages.github.io/nilmat/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/nilmat/releases/download/v1.4.1/nilmat-1.4.1.tar.gz
    - name: .tar.bz2
      url: https://github.com/gap-packages/nilmat/releases/download/v1.4.1/nilmat-1.4.1.tar.bz2

abstract: |
    The <span class="pkgname">Nilmat</span> package contains methods for checking whether a finitely generated matrix group over a finite field or the field of rational numbers is nilpotent, methods for computing with such nilpotent matrix groups and methods for constructing important classes of such nilpotent matrix groups.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    nilpotent groups, matrix groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>DEF22</span>]   <b class='BibAuthor'>Detinko, A., Eick, B. and Flannery, D.</b>,
     <i class='BibTitle'>Nilmat, Computing with nilpotent matrix groups,
             Version 1.4.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/nilmat">https://gap-packages.github.io/nilmat</a></span>.
    </p>
    

bibtex: |
    @misc{ Nilmat1.4.1,
      author =           {Detinko, A. and Eick, B. and Flannery, D.},
      title =            {{Nilmat},  Computing  with  nilpotent  matrix  groups,
                          {V}ersion 1.4.1},
      month =            {Feb},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/nilmat}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{nilmat}}},
      keywords =         {nilpotent groups; matrix groups},
      printedkey =       {DEF22}
    }

