# Nilmat, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nilmat01.tst");

# doc/examples.xml:9-12
gap> g1 := MaximalAbsolutelyIrreducibleNilpotentMatGroup(52,3,3);
<matrix group with 7 generators>

# doc/examples.xml:14-17
gap> g2 := MaximalAbsolutelyIrreducibleNilpotentMatGroup(180,11,2);
<matrix group with 41 generators>

# doc/examples.xml:19-22
gap> MaximalAbsolutelyIrreducibleNilpotentMatGroup(210,2,10);
fail

# doc/examples.xml:26-29
gap> g3 := MonomialNilpotentMatGroup(450);
<matrix group with 24 generators>

# doc/examples.xml:31-34
gap> g4 := ReducibleNilpotentMatGroup(3,180,11,2);
<matrix group with 82 generators>

# doc/examples.xml:37-40
gap> g5 := ReducibleNilpotentMatGroup(7,36);
<matrix group with 72 generators>

# doc/examples.xml:53-56
gap> IsNilpotentMatGroup(GL(200,Integers));
false

# doc/examples.xml:57-60
gap> IsNilpotentMatGroup(GL(150,11^3));
false

# doc/examples.xml:61-66
gap> g6 := MaximalAbsolutelyIrreducibleNilpotentMatGroup(127,2,7);
<matrix group with 3 generators>
gap> IsNilpotentMatGroup(g6);
true

# doc/examples.xml:67-74
gap> g7 := MonomialNilpotentMatGroup(350);
<matrix group with 6 generators>
gap> IsNilpotentMatGroup(g7);
true
gap> IsFiniteNilpotentMatGroup(g7);
true

# doc/examples.xml:75-82
gap> g8 := ReducibleNilpotentMatGroup(6,35);
<matrix group with 5 generators>
gap> IsNilpotentMatGroup(g8);
true
gap> IsFiniteNilpotentMatGroup(g8);
false

# doc/examples.xml:83-91
gap> g9 := ReducibleNilpotentMatGroup(2,36,5,2);
<matrix group with 21 generators>
gap> x := SylowSubgroupsOfNilpotentFFMatGroup(g9);;
gap> List(x, g -> Length(GeneratorsOfGroup(g)));
[ 5, 6, 1 ]
gap> IsCompletelyReducibleNilpotentMatGroup(g9);
false

# doc/examples.xml:92-99
gap> g10 := MaximalAbsolutelyIrreducibleNilpotentMatGroup(24,5,2);
<matrix group with 17 generators>
gap> SizeOfNilpotentMatGroup(g10);
173946175488
gap> IsCompletelyReducibleNilpotentMatGroup(g10);
true

# doc/examples.xml:100-107
gap> g11 := MonomialNilpotentMatGroup(96);
<matrix group with 31 generators>
gap> SizeOfNilpotentMatGroup(g11);
6442450944
gap> IsCompletelyReducibleNilpotentMatGroup(g11);
true

# doc/examples.xml:113-126
gap> L0 := NilpotentPrimitiveMatGroups(2,3,1);
[ Group([ [ [ 0*Z(3), Z(3)^0 ], [ Z(3)^0, Z(3)^0 ] ] ]), 
  Group([ [ [ Z(3)^0, 0*Z(3) ], [ 0*Z(3), Z(3)^0 ] ], 
      [ [ Z(3), Z(3)^0 ], [ Z(3), Z(3) ] ], 
      [ [ Z(3)^0, 0*Z(3) ], [ 0*Z(3), Z(3) ] ] ]), 
  Group([ [ [ Z(3)^0, 0*Z(3) ], [ 0*Z(3), Z(3)^0 ] ], 
      [ [ 0*Z(3), Z(3)^0 ], [ Z(3), 0*Z(3) ] ], 
      [ [ Z(3), Z(3) ], [ Z(3), Z(3)^0 ] ] ]) ]
gap> SizesOfNilpotentPrimitiveMatGroups(2,3,1);
[ 8, 16, 8 ]
gap> List(L0,Size);
[ 8, 16, 8 ]

# doc/examples.xml:127-138
gap> L1 := NilpotentPrimitiveMatGroups(2,2,10);;
gap> Length(L1);
40
gap> Size(L1[38]);
209715
gap> s := SizesOfNilpotentPrimitiveMatGroups(2,2,10);
[ 5, 15, 25, 41, 55, 75, 123, 155, 165, 205, 275, 451, 465, 615, 775, 825, 
  1025, 1271, 1353, 1705, 2255, 2325, 3075, 3813, 5115, 6355, 6765, 8525, 
  11275, 13981, 19065, 25575, 31775, 33825, 41943, 69905, 95325, 209715, 
  349525, 1048575 ]

# doc/examples.xml:139-143
gap> L2 := NilpotentPrimitiveMatGroups(55,3,1);;
gap> Length(L2);
114

# doc/examples.xml:144-148
gap> L3 := NilpotentPrimitiveMatGroups(6,3,3);;
gap> Length(L3);
110

# doc/examples.xml:149-153
gap> L4 := NilpotentPrimitiveMatGroups(22,11,1);;
gap> Length(L4);
1002

#
gap> STOP_TEST("nilmat01.tst", 1);
